config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: %I[show]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.valid?
      @restaurant.save!
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/new', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant, only: %I[index new create]
  def index
    @reviews = Review.all
  end
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
  if @review.save
    redirect_to restaurant_path(@restaurant)
  else
    render 'restaurants/new', status: :unprocessable_entity
  end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address  %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number  %>
  <%= f.label :category %>
  <%= f.text_field :category  %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h3>Toutes les Restaurants :</h3>

<ul>
<% @restaurants.each do |restaurant| %>
<li>
  <h2><%= link_to restaurant.name, restaurant %></h2>
</li>
<% end %>
</ul>
<hr>
<%= link_to '+ Add restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h4>New Restaurant</h4>

<%= render "form", restaurant: @restaurant %>

<%= link_to 'back',restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<section>
<h5>content</h5>
  <p>Addr : <%= @restaurant.address %></p>
  <p>Phone : <%= @restaurant.phone_number %></p>
  <p>category : <%= @restaurant.category %></p>
</section>

<div class="buttons">
<%= link_to 'all reviews', restaurant_reviews_path(@restaurant) %>
<%= link_to 'all restaurants', restaurants_path %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating, input_html: { type: 'number' } %>
  <%= f.label :content %>
  <%= f.text_field :content  %>
  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<h3>Toutes les Reviews :</h3>

<ul>
<% @reviews.each do |review| %>
<li>
  <h2><%= review.rating %></h2>
  <p><%= review.content %></p>
</li>
<% end %>
</ul>
<hr>
<%= link_to '+ Add review', new_restaurant_review_path %>

app/views/reviews/new.html.erb
<h4>New Review</h4>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating, input_html: { type: 'number' } %>
  <%= f.label :content %>
  <%= f.text_field :content  %>
  <%= f.submit %>
<% end %>

<%= link_to 'back', restaurant_reviews_path(@restaurant) %>